database-threads: 2
hikari-pool: 2
scoreboard-tick: 10

disguise:
  - alphaWolf
  - silverSword
  - stealthNinja
  - darkShadow
  - blazingPhoenix
  - quickSilver
  - lunarEclipse
  - stormChaser
  - electricJolt
  - crimsonFang
  - frostyFalcon
  - slyFox
  - wildWhisper
  - ironWarden
  - rubyRider
  - thunderStrike
  - goldenEagle
  - shadowDancer
  - icyViper
  - nightHawk
  - blazingBullet
  - cosmicComet
  - lunarLion
  - stormSurge
  - cyberSphinx
  - fieryFalcon
  - stealthyShade
  - phoenixFury
  - swiftBlade
  - silverSerpent
  - thunderBlitz
  - crimsonFury
  - frostbite
  - moonlitShadow
  - stormSword
  - electricEmber
  - goldenGryphon
  - ghostlyGaze
  - iceSaber
  - nightWraith
  - blazingBolt
  - astralAce
  - lunarLeopard
  - tempestRider
  - cyberFang
  - fieryFeather
  - stealthDragon
  - crimsonClaw
  - frostFire
  - moonlightMage
  - thunderHeart
  - silverSwan
  - phantomShade
  - shadowStalker
  - rapidRaven
  - cosmicCrusher
  - lunarLynx
  - stormStrider
  - electricEagle
  - rubyRage
  - frozenFlame
  - nightSorcerer
  - blazingBanshee
  - astralAlchemist
  - silverSpecter
  - ghostlyGolem
  - icyInferno
  - stormSpectre
  - shadowSlayer
  - quickSilhouette
  - crimsonCobra
  - frostFalcon
  - moonlightMarauder
  - thunderTamer
  - goldenGazelle
  - blazingBreeze
  - stealthStalker
  - darkDemon
  - fieryFeline
  - swiftShadow
  - silverShard
  - electricEnigma
  - cosmicChaos
  - lunarLancer
  - stormScorpion
  - cyberCentaur
  - frostyFlame
  - moonlitMystery
  - thunderousTornado
  - crimsonCrest
  - astralArcher
  - fieryFury
  - stealthySpirit
  - shadowSerpent
  - quickQuasar
  - frozenFalcon
  - lunarLich
  - stormSaber
  - electricEel
  - rubyRacer
  - darkDrake
  - blazingBoltz
  - solarKnight
  - arcaneWizard
  - shadowWalker
  - frostbite404
  - thunderDragon
  - cosmicCrusher99
  - blazingBerserker
  - astralAssassin
  - silverShooter
  - stormStrider23
  - fieryFeline87
  - stealthyNinja
  - crimsonConqueror
  - frostyFalcon51
  - moonlitMage77
  - thunderBlitz13
  - lunarLion98
  - electricJolt22
  - cyberSphinx42
  - alphaWolf35
  - silverSword62
  - stealthNinja17
  - darkShadow49
  - blazingPhoenix28
  - quickSilver81
  - lunarEclipse55
  - stormChaser73
  - electricJolt11
  - crimsonFang96